# -*- coding: utf-8 -*-
"""Student FAQ Chatboat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R-f7hO9AybEyNB05-shL8299l2at2W-i

# **Importing Libraries**
"""

!pip install -U langchain langchain-community langchain-core
!pip install pypdf faiss-cpu sentence-transformers

"""# Load **Data**"""

from langchain_community.document_loaders import PyPDFLoader
loader = PyPDFLoader("AI_notes.pdf")
docs = loader.load()
print("Pages:", len(docs))

"""# **Chunking**"""

from langchain_text_splitters import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)
documents = text_splitter.split_documents(docs)
print("Chunks:", len(documents))

"""# **Embeedings**"""

from langchain_community.embeddings import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings()

"""# **Vector Database FAISS**"""

from langchain_community.vectorstores import FAISS
db = FAISS.from_documents(documents, embeddings)

"""# **Retrieval**"""

query = "What is Artificial Intelligence?"
results = db.similarity_search(query, k=2)
print(results[0].page_content)

"""# **Queries**"""

questions = [
    "What is AI?",
    "Explain Machine Learning",
    "Advantages of Artificial Intelligence"
]

for q in questions:
  docs = db.similarity_search(q)
  print("\nQUESTION:", q)
  print("ANSWER:", docs[0].page_content)